### ISSUE TITLE
error on installation with npm

### ISSUE THREAD

**Issue by derhuerst** [zsoltc/worley-noise#3]
`npm i worley-noise` (from github) gives me the following.

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "i" "--production"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.8
npm ERR! path /Users/j/web/algorithmic-vomit/node_modules/worley-noise
npm ERR! code EISGIT

npm ERR! git /Users/j/web/algorithmic-vomit/node_modules/worley-noise: Appears to be a git repo or submodule.
npm ERR! git     /Users/j/web/algorithmic-vomit/node_modules/worley-noise
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/j/web/algorithmic-vomit/npm-debug.log
```

It seems like the `bin` dir in the GitHub repo contains a Webpack-built version. Because it is not included in the NPM version, installation fails. I'd suggest removing `bin` entirely, as there's no purpose in a single webpack-wrapped lib.

EDIT: webpack-built dist files make sense. But in npm they shouldn't be included nonetheless.

**Comment by derhuerst** [comment]
#4 fixed this as far as i remember.

@zsoltc Would you mind publishing to npm?

**Comment by zsoltc** [comment]
@derhuerst 
Published. :)
https://www.npmjs.com/package/worley-noise
